title: Elastic Logstash and Filebeat default index patterns
order: 20
backends:
  - es-qs
  - es-dsl
  - kibana
  - xpack-watcher
  - elastalert
  - elastalert-dsl
defaultindex:
    - logstash-*
    - filebeat-*
